config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos

  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
  end
  
  def create
    @todo = Todo.new params.require(:todo).permit :description

    if @todo.save
      redirect_to action: 'index'
    else
      redirect_to({ action: 'index' }, alert: 'Invalid data')
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h2>Todo List</h2>

<% if alert %>
  <%= alert %>
  <br>
<% end %>
<br>

<%= form_with scope: :todo, url: todos_path do |form| %>
  <%= form.text_field :description, placeholder: 'Description' %>
  <%= form.submit 'Add' %>
<% end %>

<br>
<table>
  <tr>
    <th>Description</th>
    <th>Status</th>
    <th></th>
  </tr>
  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.description %></td>
      <td><%= check_box_tag todo.status %></td>
      <td><%= link_to 'Remove', todo_path(todo),
        method: :delete,
        data: { confim: 'Are you sure?' }%>
      </td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h2>Add a new Todo</h2>

<%= form_with scope: :todo, url: todos_path, local: true do |form| %>
  <table>
    <tr>
      <th>
        <%= form.label :description %>
      </th>
      <th>
        <%= form.label :status %>
      </th>
    </tr>
    <tr>
      <td>
        <%= form.text_field :description %>
      </td>
      <td>
        <%= form.check_box :status %>
      </td>
      <td><%= form.submit "Add" %></td>
    </tr>
  </table>
<% end %>

app/views/todos/show.html.erb
<p>
  <strong><%= @todo.description %></strong>
  <%= @todo.status %>
</p>